server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/douglasribeiro/ms-course-configs
          search-paths: 'greeting-service*'
#        default-label: main
#  profiles:
#    active:
#    - native